### PR TITLE
doc: Update README.md to include WIP status

### PR DESCRIPTION
**Pull request by mhdawson**
Based on the EP for the stable module ABI I think
an additional status would be useful to call out
those which we believe are ready for final review
versus those that we expect to iterate on before
that final review should take place.

### CODE REVIEW

**Comment by jasnell** [comment]
I've always disliked "incubating" as a status. Perhaps just "pre-draft"?

**Comment by mhdawson** [comment]
or maybe "WIP" for work in progress ? otherwise "pre-draft" is fine with me.

**Comment by evanlucas** [comment]
I like WIP

**Comment by jasnell** [comment]
Work in progress works for me too

**Comment by mhdawson** [comment]
Updated to use WIP

**Comment by mhdawson** [comment]
Any additional comments ?

@trevnorris I know you had some on the other PR where the change had been accidentally included.

**Comment by trevnorris** [comment]
I'm not sure if I completely agree with how this works. Documents can land as DRAFT while they're being revised. A WIP to me means that the PR is asking for help to review/fix/etc. That's easily enough placed in the title of the PR. I don't like the idea of a document landing with WIP, since it denotes that it's definitely not something even potentially accepted. A document should land unless it's been agreed upon that it could be implemented.

**Comment by mhdawson** [comment]
Long since stale.  node-eps has been sunset.

**Pull request closed without merging**
